### ISSUE TITLE
Feature Request: Alias fees get progressively larger the more aliases you create

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-node#531] opened 2021-08-22 04:40 UTC
Feature Request: Alias fees get progressively larger the more aliases you create.

This would stop someone from using a dictionary script and grabbing all the aliases leaving nothing for anyone else.

https://europe.signum.network/burst?requestType=getAliases&account=12699053857721649381 for an example

These fees go directly to SNA.

You get 5 aliases assigned to your address for low fee.

Next 5 are 100 Signa.
Next 5 are 500 Signa
Next 5 are 1000 Signa
Next 5 are 2000 Signa
Etc

**Comment by dompie** [comment] 2021-08-22 21:20
I would like to elaborate more, as what the goals and options may be. I do not know why aliases were implemented in the past. The most expected purpose from my point of view is to have another valid name for the own wallet aside from the main name. So friends from different games/communities can find you (or your wallet) at Signum more easy. I call this  the "main purpose".

If we, the community, agree on using aliases for that main purpose, we should really prevent people and future actors to register more then X amount of aliases per wallet. That rises questions like:
1. What will happen with wallets/accounts that already have more then X aliases registred?
2. What amount of aliases is assumed as "valid"? Is it 3, 13 or even 3000?

There is also the possibility to establish a business model around aliases and accept an unlimited amount of aliases around per wallet/account. And charge each wallet/account a fee for holding an alias. As stated by @paulpoco this might be an opportunity to help funding SNA (Signum Network Association - https://sna.signum.network/) . But again, there are questions and conditions to make up:
**A**. Is it ok to have a business model around aliases? If yes, what conditions?
**B**. Do we want to do some regulations? 
**C**. What is the proper way for charging alias fees. Should SNA do this or should a license be sold to a company/individual that just passes the money to SNA and promotes/sells signum aliases on its own?
**D**. If there is a fee/charge. Is it one-time fee, or recurring fee?
**E**. When designing this feature keep in mind to not be reward opening multiple accounts just to have cheaper aliases.

Are there other wise possibilities not stated above? We may also "sell" a license to handle aliases to an coin exchange in return to get a direct USD <-> SIGNA listing (if an exchange finds this attractive...well, why not?).

Another also a (in my point of view) strong argument for a limited number of aliases: Besides of transactions - the aliase feature currently has a clear impact on transaction performance of signum network. The problem is already addressed by the developers - but do we want another load-producing feature on the chain? Aliases just have a meaning to the account/wallet holder and do not produce any meaningful money-flow/turnover.
Transactions do, as there a always at least two accounts involved. IMHO that kind of transaction should have always higher priority. Just to protect the performance of the signum network and make sure that peoples cash keeps flowing. It's not worth it if someone spend 3,675 signa (or even 3675) on aliases and real transaction will be hit with a big delay.

**Comment by jjos2372** [comment] 2022-04-23 13:30
Hello, thanks for the input and suggestions. However, no solution "per account" would accomplish the desired result. People can just create new accounts and do the same up to the limit. Closing this for now.

**Closed by jjos2372** 2022-04-23 13:30 UTC
